# Python 3.10.12 tabanlı resmi imajı kullan
FROM python:3.10.12-slim

# Çalışma dizini ayarla
WORKDIR /app

# Gereksinimleri kopyala ve yükle
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Tüm kodu kopyala
COPY . .

# Render'ın verdiği PORT'u environment variable olarak ayarla
ENV PORT=8020

# Flask uygulamasının dinleyeceği portu expose et
EXPOSE 8020

# Uygulamayı başlat
CMD ["python", "main.py"]
